"""Write the monthly summary back to Excel in the layout the business already uses."""

from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Font
from openpyxl.utils import get_column_letter

from sheet_to_pipeline.legacy import BUSINESS, SUMMARY_HEADER
from sheet_to_pipeline.reconcile import MonthCheck, pipeline_summary

WIDTHS = [12, 14, 10, 10, 12, 12, 12, 12, 16]


def write_excel_report(db_path: Path, checks: list[MonthCheck], path: Path) -> Path:
    """Summary sheet laid out like the old tab, plus a Checks sheet of what changed and why."""
    workbook = Workbook()
    summary = workbook.active
    assert summary is not None
    summary.title = "Summary"
    summary.append([f"{BUSINESS} - Monthly Sales Summary"])
    summary.append(["Generated by the sales pipeline from the monthly exports. Do not edit."])
    summary.append([])
    summary.append(SUMMARY_HEADER)
    summary["A1"].font = Font(bold=True, size=14)
    for cell in summary[4]:
        cell.font = Font(bold=True)
    for label, (_, values) in pipeline_summary(db_path).items():
        summary.append([label, *(values[measure] for measure in SUMMARY_HEADER[1:])])
        for column in (2, 5, 6, 7, 8):
            summary.cell(summary.max_row, column).number_format = "#,##0.00"
    for index, width in enumerate(WIDTHS, start=1):
        summary.column_dimensions[get_column_letter(index)].width = width

    notes = workbook.create_sheet("Checks")
    notes.append(["Month", "Status", "Revenue before", "Revenue now", "Change", "Why"])
    for cell in notes[1]:
        cell.font = Font(bold=True)
    for check in checks:
        revenue = next((d for d in check.differences if d.measure == "Revenue"), None)
        why = " ".join(cause.summary for cause in check.causes) or "Matches the old workbook."
        notes.append(
            [
                check.label,
                check.status,
                revenue.workbook if revenue else None,
                revenue.pipeline if revenue else None,
                check.revenue_gap or None,
                why,
            ]
        )
    notes.column_dimensions["F"].width = 90
    path.parent.mkdir(parents=True, exist_ok=True)
    workbook.save(path)
    return path
